# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
timezone: Asia/Tokyo
title: "RyukyuInteractive Tech Blog"
email: ""
description: > # this means to ignore newlines until "baseurl:"
  Be the leading internet company by creative technologies
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech.ryukyu-i.co.jp" # the base hostname & protocol for your site
twitter_username: ""
github_username:  "RyukyuInteractive"

google_analytics: "UA-84396323-1"
disqus_shortname: "ri-tech"
comments: true

# Build settings
markdown: kramdown
# theme: minima

# social settings
twitter_card: "summary_large_image"

gems:
  - jekyll-paginate
  - jekyll-mentions
  - jemoji

permalink: pretty
paginate: 3
paginate_path: "/page/:num/"

author:
  name     : "RyukyuInteractive"
  bio      : "Be the leading internet company by creative technologies"

# Exclude these files from your production _site
exclude:
  - _dev
  - node_modules
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - package.json
  - gulpfile.babel.js
  - webpack.config.js
  - .babelrc
  - .editorconfig
  - .ruby-version

